### ISSUE TITLE
AWS peer resource import  causes crash

### ISSUE THREAD

**Issue by dxciberaws** [AviatrixSystems/terraform-provider-aviatrix#925]
**Describe the problem**

Importing the following resource:

```
resource "aviatrix_aws_peer" "sec-sbx" {
  account_name1 = aviatrix_account.dxciber-sec.account_name
  account_name2 = aviatrix_account.dxciber-sbx.account_name
  vpc_id1 = data.aws_cloudformation_stack.vpcStack-SEC.outputs["VPCId"]
  vpc_id2 = data.aws_cloudformation_stack.vpcStack-SBX.outputs["VPCId"]
  vpc_reg1 = local.region
  vpc_reg2 = local.region
  rtb_list1 = [data.aws_cloudformation_stack.vpcStack-SEC.outputs["AZASSLVPNSubnetRtId"],
               data.aws_cloudformation_stack.vpcStack-SEC.outputs["AZBSSLVPNSubnetRtId"],
               data.aws_cloudformation_stack.vpcStack-SEC.outputs["AZAPrivateRtId"],
               data.aws_cloudformation_stack.vpcStack-SEC.outputs["AZBPrivateSubnetRtId"]]
  rtb_list2 = ["all"]
}
```

Causes:

```
aviatrix_aws_peer.sec-sbx: Importing from ID "pcx-HIDDEN"...
aviatrix_aws_peer.sec-sbx: Import prepared!
  Prepared aviatrix_aws_peer for import
aviatrix_aws_peer.sec-sbx: Refreshing state... [id=pcx-HIDDEN]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [1] with length 1
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: goroutine 84 [running]:
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/AviatrixSystems/terraform-provider-aviatrix/v2/aviatrix.resourceAviatrixAWSPeerRead(0xc00030e780, 0x195e6a0, 0xc0000864e0, 0xc00008b610, 0xc00052ec30)
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    github.com/AviatrixSystems/terraform-provider-aviatrix/v2/aviatrix/resource_aviatrix_aws_peer.go:127 +0xdda
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000172840, 0x1adf160, 0xc000310b80, 0xc00030e780, 0x195e6a0, 0xc0000864e0, 0x0, 0x0, 0x0)
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:290 +0x95
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000172840, 0x1adf160, 0xc000310b80, 0xc0001ba770, 0x195e6a0, 0xc0000864e0, 0xc0000068b8, 0x0, 0x0, 0x0)
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:564 +0x1cb
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002310a0, 0x1adf160, 0xc000310b80, 0xc000310bc0, 0xc000310b80, 0x18f3680, 0x1923760)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:575 +0x45b
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0003f58e0, 0x1adf160, 0xc000310b80, 0xc0000869c0, 0xc0003f58e0, 0xc0003b9590, 0xc0001d3ba0)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x108
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1923760, 0xc0003f58e0, 0x1adf220, 0xc0003b9590, 0xc000086960, 0x0, 0x1adf220, 0xc0003b9590, 0xc00052ea90, 0xce)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a68c0, 0x1ae9260, 0xc000084900, 0xc000512400, 0xc000300810, 0x1f986b0, 0x0, 0x0, 0x0)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    google.golang.org/grpc@v1.34.0/server.go:1210 +0x522
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: google.golang.org/grpc.(*Server).handleStream(0xc0002a68c0, 0x1ae9260, 0xc000084900, 0xc000512400, 0x0)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    google.golang.org/grpc@v1.34.0/server.go:1533 +0xd25
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003d8140, 0xc0002a68c0, 0x1ae9260, 0xc000084900, 0xc000512400)
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    google.golang.org/grpc@v1.34.0/server.go:871 +0xa8
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe:    google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd
2021-04-30T12:29:16.339+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/04/30 12:29:16 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/30 12:29:16 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/30 12:29:16 [TRACE] [walkImport] Exiting eval tree: import aviatrix_aws_peer.sec-sbx result
2021/04/30 12:29:16 [TRACE] vertex "import aviatrix_aws_peer.sec-sbx result": visit complete
2021/04/30 12:29:16 [TRACE] vertex "aviatrix_aws_peer.sec-sbx (import id \"pcx-HIDDEN\")": dynamic subgraph encountered errors
2021/04/30 12:29:16 [TRACE] vertex "aviatrix_aws_peer.sec-sbx (import id \"pcx-HIDDEN\")": visit complete
2021/04/30 12:29:16 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/aviatrixsystems/aviatrix\"] (close)" errored, so skipping
2021/04/30 12:29:16 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-04-30T12:29:16.350+0200 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/aviatrixsystems/aviatrix/2.18.2/windows_amd64/terraform-provider-aviatrix_v2.18.2.exe pid=14248 error="exit status 2"
2021-04-30T12:29:16.350+0200 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**To Reproduce**

terraform import aviatrix_aws_peer.sec-sbx pcx-HIDDEN

**Expected behavior**

Successful import of the resource

The resource already existed in the state and was removed from the state in the process of troubleshooting a the following other error happening when running terraform plan:

```
Error: invalid character '<' looking for beginning of value

  on VPN-main.tf line 11, in provider "aviatrix":
  11: provider "aviatrix" {
```
**Additional data / screenshots**
Include any relevant tf files.

**Environment:**
 - Provider version
 - Terraform version
 - Aviatrix Controller version

**Additional context**

Whole module is unmanageable due to crashing of this resource.

Stack trace in crash.log:

```
2021-04-30T12:29:16.329+0200 [INFO]  plugin.terraform-provider-aviatrix_v2.18.2.exe: 2021/04/30 12:29:16 [DEBUG] Looks like an import, no vpc id received. Import Id is pcx-HIDDEN: timestamp=2021-04-30T12:29:16.329+0200
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: panic: runtime error: index out of range [1] with length 1
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: goroutine 84 [running]:
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/AviatrixSystems/terraform-provider-aviatrix/v2/aviatrix.resourceAviatrixAWSPeerRead(0xc00030e780, 0x195e6a0, 0xc0000864e0, 0xc00008b610, 0xc00052ec30)
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	github.com/AviatrixSystems/terraform-provider-aviatrix/v2/aviatrix/resource_aviatrix_aws_peer.go:127 +0xdda
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000172840, 0x1adf160, 0xc000310b80, 0xc00030e780, 0x195e6a0, 0xc0000864e0, 0x0, 0x0, 0x0)
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:290 +0x95
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000172840, 0x1adf160, 0xc000310b80, 0xc0001ba770, 0x195e6a0, 0xc0000864e0, 0xc0000068b8, 0x0, 0x0, 0x0)
2021-04-30T12:29:16.333+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/resource.go:564 +0x1cb
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002310a0, 0x1adf160, 0xc000310b80, 0xc000310bc0, 0xc000310b80, 0x18f3680, 0x1923760)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.2/helper/schema/grpc_provider.go:575 +0x45b
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0003f58e0, 0x1adf160, 0xc000310b80, 0xc0000869c0, 0xc0003f58e0, 0xc0003b9590, 0xc0001d3ba0)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x108
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1923760, 0xc0003f58e0, 0x1adf220, 0xc0003b9590, 0xc000086960, 0x0, 0x1adf220, 0xc0003b9590, 0xc00052ea90, 0xce)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a68c0, 0x1ae9260, 0xc000084900, 0xc000512400, 0xc000300810, 0x1f986b0, 0x0, 0x0, 0x0)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	google.golang.org/grpc@v1.34.0/server.go:1210 +0x522
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: google.golang.org/grpc.(*Server).handleStream(0xc0002a68c0, 0x1ae9260, 0xc000084900, 0xc000512400, 0x0)
2021-04-30T12:29:16.334+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	google.golang.org/grpc@v1.34.0/server.go:1533 +0xd25
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003d8140, 0xc0002a68c0, 0x1ae9260, 0xc000084900, 0xc000512400)
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	google.golang.org/grpc@v1.34.0/server.go:871 +0xa8
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-30T12:29:16.335+0200 [DEBUG] plugin.terraform-provider-aviatrix_v2.18.2.exe: 	google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd
```
Issue also happened with 2.17.2. As part of the troubleshooting, Controller was upgraded to latest version and as required, plugin updated to 2.18.2.

**Comment by dxciberaws** [comment]
Crash issue seems related to using the controller's DNS name instead of its IP address. However, when using the IP the following error remains:

```
Error: invalid character '<' looking for beginning of value
```

Closing this issue and opening new for the remaining error
